// AUTO-GENERATED by WaratahCmd.exe (https://github.com/microsoft/hidtools)
// Adopted for Rust by Szczurek

// HID Usage Tables: 1.6.0
// Descriptor size: 31 (bytes)
// +----------+-------+-------------------+
// | ReportId | Kind  | ReportSizeInBytes |
// +----------+-------+-------------------+
// |        1 | Input |                 1 |
// +----------+-------+-------------------+
pub const HID_REPORT_DESCRIPTOR: [u8; 31] = [
    0x05, 0x0C, // UsagePage(Consumer[0x000C])
    0x09, 0x01, // UsageId(Consumer Control[0x0001])
    0xA1, 0x01, // Collection(Application)
    0x85, 0x01, //     ReportId(1)
    0x09, 0xE9, //     UsageId(Volume Increment[0x00E9])
    0x09, 0xEA, //     UsageId(Volume Decrement[0x00EA])
    0x09, 0xE2, //     UsageId(Mute[0x00E2])
    0x15, 0x00, //     LogicalMinimum(0)
    0x25, 0x01, //     LogicalMaximum(1)
    0x95, 0x03, //     ReportCount(3)
    0x75, 0x01, //     ReportSize(1)
    0x81,
    0x02, //     Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x95, 0x01, //     ReportCount(1)
    0x75, 0x05, //     ReportSize(5)
    0x81,
    0x03, //     Input(Constant, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0xC0, // EndCollection()
];

pub const HID_REPORT_INPUT_ID: u8 = 1;
